### ISSUE TITLE
关于lcf_bert问题

### ISSUE THREAD

**Issue by neolcx** [songyouwei/ABSA-PyTorch#100]
loading vocabulary file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at C:\Users\lcx\.pytorch_pretrained_bert\26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz not found in cache, downloading to C:\Users\lcx\AppData\Local\Temp\tmp95vi8kd2
 30%|██▉       | 120810496/407873900 [15:50<1:43:53, 46052.13B/s]Model name 'bert-base-uncased' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz' was a path or url but couldn't find any file associated to this path or url.
Traceback (most recent call last):
  File "E:\Pycharm\PyCharm 2018.3.3\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "E:\Pycharm\PyCharm 2018.3.3\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "E:\Pycharm\PyCharm 2018.3.3\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "E:\Pycharm\PyCharm 2018.3.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "G:/Aspect_sentiment/ABSA-PyTorch-master/train.py", line 290, in <module>
    main()
  File "G:/Aspect_sentiment/ABSA-PyTorch-master/train.py", line 285, in main
    ins = Instructor(opt)
  File "G:/Aspect_sentiment/ABSA-PyTorch-master/train.py", line 36, in __init__
    self.model = opt.model_class(bert, opt).to(opt.device)
  File "G:\Aspect_sentiment\ABSA-PyTorch-master\models\lcf_bert.py", line 34, in __init__
    self.bert_SA = SelfAttention(bert.config, opt)
AttributeError: 'NoneType' object has no attribute 'config'
请问以下这个问题怎么解决

**Comment by yangheng95** [comment]
您好，这个问题是由于亚马逊aws服务器链接不稳定导致下载失败，建议在网络状况较好时下载该模型。

**Comment by neolcx** [comment]
感谢您的解答，您好您有下好的模型吗可以云盘分享一下吗，感谢
