### ISSUE TITLE
SqueezeEmbedding 层

### ISSUE THREAD

**Issue by SStarLib** [songyouwei/ABSA-PyTorch#68]
Traceback (most recent call last):
  File "/Users/wei/Desktop/pythonDemo/nlpdazuoye/nlp_absa/demo2.py", line 479, in <module>
    train()
  File "/Users/wei/Desktop/pythonDemo/nlpdazuoye/nlp_absa/demo2.py", line 475, in train
    ins.run()
  File "/Users/wei/Desktop/pythonDemo/nlpdazuoye/nlp_absa/demo2.py", line 403, in run
    best_model_path = self._train(criterion, optimizer, train_data_loader, val_data_loader) # 保存最好的模型
  File "/Users/wei/Desktop/pythonDemo/nlpdazuoye/nlp_absa/demo2.py", line 327, in _train
    outputs = self.model(inputs)
  File "/Users/wei/anaconda3/envs/tensorflow/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/wei/Desktop/pythonDemo/nlpdazuoye/nlp_absa/demo2.py", line 218, in forward
    target = self.squeeze_embedding(target, target_len)
  File "/Users/wei/anaconda3/envs/tensorflow/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/wei/Desktop/pythonDemo/nlpdazuoye/nlp_absa/demo2.py", line 70, in forward
    x_emb_p = torch.nn.utils.rnn.pack_padded_sequence(x, x_len, batch_first=self.batch_first)
  File "/Users/wei/anaconda3/envs/tensorflow/lib/python3.6/site-packages/torch/nn/utils/rnn.py", line 268, in pack_padded_sequence
    torch._C._VariableFunctions._pack_padded_sequence(input, lengths, batch_first)
RuntimeError: Length of all samples has to be greater than 0, but found an element in 'lengths' that is <= 0

这种错误 不知道怎么回事

**Comment by songyouwei** [comment]
看错误提示，应该是因为输入的这个batch的序列里，包含了length为0的sequence。建议先确认自己了解这个层的作用（#31），然后检查一下输入内容的格式是不是符合要求。

**Comment by SStarLib** [comment]
> 看错误提示，应该是因为输入的这个batch的序列里，包含了length为0的sequence。建议先确认自己了解这个层的作用（#31），然后检查一下输入内容的格式是不是符合要求。

嗯嗯，已查到问题，并解决。谢谢！
