### ISSUE TITLE
BertModel: unexpected keyword argument 'output_all_encoded_layers'

### ISSUE THREAD

**Issue by fhamborg** [songyouwei/ABSA-PyTorch#88]
Using the latest versions and using AEN_BERT, I get the following error:

```
Traceback (most recent call last):
  File "/Users/felix/IdeaProjects/ABSA-PyTorch/train.py", line 292, in <module>
    main()
  File "/Users/felix/IdeaProjects/ABSA-PyTorch/train.py", line 288, in main
    ins.run()
  File "/Users/felix/IdeaProjects/ABSA-PyTorch/train.py", line 169, in run
    best_model_path = self._train(criterion, optimizer, train_data_loader, val_data_loader)
  File "/Users/felix/IdeaProjects/ABSA-PyTorch/train.py", line 104, in _train
    outputs = self.model(inputs)
  File "/Users/felix/anaconda3/envs/cope/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/felix/IdeaProjects/ABSA-PyTorch/models/aen.py", line 107, in forward
    context, _ = self.bert(context, output_all_encoded_layers=False)
  File "/Users/felix/anaconda3/envs/cope/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'output_all_encoded_layers'

Process finished with exit code 1
```

**Comment by songyouwei** [comment]
Have you solved the problem yet?

**Comment by fhamborg** [comment]
Yes, it happened as part of the transition from pytorch-pretrained-bert to transformers, see https://github.com/huggingface/transformers#Migrating-from-pytorch-pretrained-bert-to-transformers :-)
