### ISSUE TITLE
size mismatch for embed.weight

### ISSUE THREAD

**Issue by shankar536** [songyouwei/ABSA-PyTorch#96]
Im Getting the following error. Please guide me how to resolve 

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\red\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\red\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\red\ABSA-Personal-Marketing-master\declines.py", line 220, in ProcessRow
    result = evalModels(key, cleaned_input, keyword)
  File "C:\red\ABSA-Personal-Marketing-master\declines.py", line 119, in evalModels
    sentiment = infer_brakeservice.main(sentence, key, './atae-lstm-cabasc/')
  File "./atae-lstm-cabasc\infer_brakeservice.py", line 92, in main
    inf = Inferer(opt, path)
  File "./atae-lstm-cabasc\infer_brakeservice.py", line 31, in __init__
    self.model.load_state_dict(torch.load(opt.state_dict_path))
  File "C:\red\ABSA-Personal-Marketing-master\venv\lib\site-packages\torch\nn\modules\module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ATAE_LSTM:
	size mismatch for embed.weight: copying a param with shape torch.Size([2882, 300]) from checkpoint, the shape in current model is torch.Size([3787, 300]).
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/red/ABSA-Personal-Marketing-master/declines.py", line 341, in <module>
    evaluateFromDB()
  File "C:/red/ABSA-Personal-Marketing-master/declines.py", line 302, in evaluateFromDB
    processed_records = async_results.get()
  File "C:\Users\red\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
RuntimeError: Error(s) in loading state_dict for ATAE_LSTM:
	size mismatch for embed.weight: copying a param with shape torch.Size([2882, 300]) from checkpoint, the shape in current model is torch.Size([3787, 300]).

**Comment by songyouwei** [comment]
Inconsistent vocabulary size. Maybe you save a model which is trained with a corpus of `3787 ` different words, and load this model with a different corpus consists of `2882 ` different words.

**Comment by shankar536** [comment]
Thanks
